image: docker:stable
services:
  - docker:dind
stages:
  - build
  - deploy
compose-up:
  stage: build
  script:
    - apk add build-base
    - apk add --no-cache py-pip
    - pip install docker-compose
    - docker-compose up -d --build
    - docker ps | grep api
    - docker ps | grep nginx
    - docker exec nginx apk add --update curl
    - docker exec nginx curl -sSk -D - "localhost/" | tac | tac | grep 301
    - docker exec nginx curl -sSk -D - "https://localhost/work/" | tac | tac | grep 200
    - docker exec nginx curl -sSk -D - "https://localhost/api/" | tac | tac | grep 403
registry:
  stage: deploy
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker build -t registry.gitlab.com/jmanmini/jacksonmoore-com-au/nginx ./nginx
    - docker push registry.gitlab.com/jmanmini/jacksonmoore-com-au/nginx
    - docker build -t registry.gitlab.com/jmanmini/jacksonmoore-com-au/api ./api
    - docker push registry.gitlab.com/jmanmini/jacksonmoore-com-au/api
    - docker build -t registry.gitlab.com/jmanmini/jacksonmoore-com-au/datadog ./datadog
    - docker push registry.gitlab.com/jmanmini/jacksonmoore-com-au/datadog
  only:
    - master
