sudo: required

language: node_js

services:
  - docker

install: true

before_script:
  - docker-compose up -d --build

script:
  - docker ps | grep -q api
  - docker ps | grep -q nginx
  - curl -sSk -D - "localhost/" | tac | tac | grep -q 301
  - curl -sSk -D - "https://localhost/work/" | tac | tac | grep -q 200
  - curl -sSk -D - "https://localhost/api/" | tac | tac | grep -q 403
after_deploy:
  - curl -X POST "https://cloud.docker.com/api/build/v1/source/326183ac-ee01-4586-9c92-2e80982d44f6/trigger/9113dc4c-496c-4041-88cc-7cbae07b77d6/call/"