version: '3'
services:
  api:
    build: ./api
    container_name: api
    restart:
      always
  nginx:
    build: ./nginx
    ports:
      - "80:80"
      - "443:443"
    restart:
      always
    depends_on:
      - api
    container_name: nginx
     