version: '3'
services:
  api:
    image: index.docker.io/jacksonsamuelmoore/jacksonmoore.com.au:api
  nginx:
    image: index.docker.io/jacksonsamuelmoore/jacksonmoore.com.au:nginx
  ouroboros:
    image: circa10a/ouroboros
    environment:
      - REPO_USER=jacksonsamuelmoore
      - REPO_PASS=Jdog20032003
      - IGNORE=shadowbox
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 30 --loglevel debug --keep-tag
    container_name:  ouroboros
  ouroboros-box:
    image: circa10a/ouroboros
    environment:
      - MONITOR=shadowbox
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 30 --loglevel debug --keep-tag
    container_name:  ouroboros-box