version: "3"
services:
  api:
    image: registry.gitlab.com/jmanmini/jacksonmoore-com-au/api
    labels:
      com.centurylinklabs.watchtower.enable: "true"
  nginx:
    image: registry.gitlab.com/jmanmini/jacksonmoore-com-au/nginx
    labels:
      com.centurylinklabs.watchtower.enable: "true"
  next:
    image: registry.gitlab.com/jmanmini/jacksonmoore-com-au/next
    labels:
      com.centurylinklabs.watchtower.enable: "true"
  watchtower:
    image: v2tec/watchtower
    environment:
      - REPO_USER=jacksonsamuelmoore
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/jacks/.docker/config.json:/config.json
    command: --interval 30 --label-enable
    container_name: watchtower
    restart: always
