version: '3'
services:
  api:
    image: index.docker.io/jacksonsamuelmoore/jacksonmoore.com.au:api
  nginx:
    image: index.docker.io/jacksonsamuelmoore/jacksonmoore.com.au:nginx
  watchtower:
    image: v2tec/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/jmanmini/.docker/config.json:/config.json
    command: --interval 30