version: "3"
services:
  api:
    build: ./api
    container_name: api
    restart: always
  next:
    build: ./next
    container_name: next
    restart: always
  nginx:
    build: ./nginx
    restart: always
    depends_on:
      - api
      - next
    ports:
      - "80:80"
      - "443:443"
    container_name: nginx
