version: '3'
services:
  api:
    image: index.docker.io/jacksonsamuelmoore/jacksonmoore.com.au:api
    labels:
      com.centurylinklabs.watchtower.enable: "true"
  nginx:
    image: index.docker.io/jacksonsamuelmoore/jacksonmoore.com.au:nginx
    labels:
      com.centurylinklabs.watchtower.enable: "true"
  watchtower:
    image: v2tec/watchtower
    environment:
      - REPO_USER=jacksonsamuelmoore
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/jmanmini/.docker/config.json:/config.json
    command: --interval 30 --label-enable --debug
    container_name:  watchtower
    restart:
      always
  ouroboros-box:
    image: circa10a/ouroboros
    environment:
      - MONITOR=shadowbox
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 30 --keep-tag
    container_name:  ouroboros-box
    labels:
      com.centurylinklabs.watchtower.enable: "false"
    restart:
      always
  datadog:
    build: index.docker.io/jacksonsamuelmoore/jacksonmoore.com.au:datadog
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /proc/:/host/proc/:ro
      - /sys/fs/cgroup/:/host/sys/fs/cgroup:ro
    environment:
      - DD_API_KEY=6592e0401695eb63273093c84550f096
    container_name:  datadog

              