version: "3"
services:
  api:
    image: registry.gitlab.com/jmanmini/jacksonmoore-com-au/api
    labels:
      com.centurylinklabs.watchtower.enable: "true"
  nginx:
    image: registry.gitlab.com/jmanmini/jacksonmoore-com-au/nginx
    labels:
      com.centurylinklabs.watchtower.enable: "true"
  watchtower:
    image: v2tec/watchtower
    environment:
      - REPO_USER=jacksonsamuelmoore
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/jacks/.docker/config.json:/config.json
    command: --interval 30 --label-enable
    container_name: watchtower
    restart: always
  ouroboros-box:
    image: circa10a/ouroboros
    environment:
      - MONITOR=shadowsocks
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 30 --keep-tag
    container_name: ouroboros-box
    labels:
      com.centurylinklabs.watchtower.enable: "false"
    restart: always
  datadog:
    image: registry.gitlab.com/jmanmini/jacksonmoore-com-au/datadog
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /proc/:/host/proc/:ro
      - /sys/fs/cgroup/:/host/sys/fs/cgroup:ro
    environment:
      - DD_API_KEY=6592e0401695eb63273093c84550f096
    container_name: datadog
    labels:
      com.centurylinklabs.watchtower.enable: "true"
    restart: always
  shadowsocks:
    image: shadowsocks/shadowsocks-libev
    ports:
      - "8388:8388"
    environment:
      - METHOD=aes-256-gcm
      - PASSWORD=9MLSpPmNt
    restart: always
    container_name: shadowsocks
    labels:
      com.centurylinklabs.watchtower.enable: "false"
