name: ci

on:
  push:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: |
          docker-compose up -d --build
          docker ps | grep api
          docker ps | grep next
          docker ps | grep nginx
          docker exec nginx apk add --update curl
          docker exec nginx curl -sSk -D - "localhost/" | tac | tac | grep 301
          docker exec nginx curl -sSk -D - "https://localhost/api/" | tac | tac | grep 403
          docker exec nginx curl -sSk -D - "https://localhost/work" | tac | tac | grep 200
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
      - name: Build and push API
        uses: docker/build-push-action@v2
        with:
          context: ./api
          file: ./api/Dockerfile
          platforms: linux/amd64
          push: true
          tags: ghcr.io/jmanmini/jacksonmoore.com.au.api:latest
      - name: Build and push NGINX
        uses: docker/build-push-action@v2
        with:
          context: ./nginx
          file: ./nginx/Dockerfile
          platforms: linux/amd64
          push: true
          tags: ghcr.io/jmanmini/jacksonmoore.com.au.nginx:latest
      - name: Build and push NextJS
        uses: docker/build-push-action@v2
        with:
          context: ./next
          file: ./next/Dockerfile
          platforms: linux/amd64
          push: true
          tags: ghcr.io/jmanmini/jacksonmoore.com.au.api:latest
